# create simple deployment yaml
apiVersion: v1
kind: Service
metadata:
  namespace: karting-ai
  name: azureml-fastapi-karting
  labels:
    app: azureml-fastapi-karting
spec:
  selector:    
    app: azureml-fastapi-karting
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP



