FROM python:3.9
WORKDIR /code
COPY ./requirements.dev.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install keras --upgrade 
COPY outputs /code/outputs
COPY main.py main.py
COPY download_model.py download_model.py
CMD ["python", "download_model.py", "&&", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
